version: "3.8"

services:
    server:
        build: server/
        ports:
            - 8000
        networks:
            - back-tier

    client:
        build: client/
        volumes:
            - ./client/src:/client/src
            - ./client/vite.config.ts:/client/vite.config.ts
        ports:
            - 3000
        networks:
            - back-tier
        depends_on:
            - server

    mongo:
        image: mongo
        ports:
            - 27017:27017
        networks:
            - back-tier

    proxy:
        image: nginx:stable-alpine
        ports:
            - 9000:9000
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - front-tier
            - back-tier
        depends_on:
            - client
            - server

networks:
    front-tier:
        attachable: true
    back-tier: {}
